[main]
git-rev = "branch:main"

[develop]
git-rev = "branch:develop"

[develop_lair_0_1]
git-rev = "branch:develop"
lair-version-req = "~0.1"

[v0_0_110]
git-rev = "commit:holochain-0.0.110"
lair-version-req = "~0.0"
